services:
  eureka-server:
    build: ./server/server
    container_name: eureka-server
    ports:
      - "8761:8761"
      
  ms-productos:
    build: ./ms-productos
    container_name: ms-productos
    ports:
      - "9095:9095"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - ms-productos
